### ISSUE TITLE
数学公式

### ISSUE THREAD

**Issue by widsnoy** [moeshin/Typecho-Theme-Littlehands#1]
请问怎么让mathjax自动刷新啊，好像不兼容pjax。QAQ

**Comment by moeshin** [comment]
:astonished: 抱歉，没注意到你的问题。

没用过 MathJax，看了一下 [文档](https://docs.mathjax.org/en/latest/advanced/typeset.html)，是调用 `MathJax.typeset()` 刷新。

把代码添加到这里应该就行了：

https://github.com/moeshin/Typecho-Theme-Littlehands/blob/a984f1a47724ded62ffb527f944c6e19f69d7510/pjax.js#L27-L31
